### ISSUE TITLE
Python Connector and Docker Setup Guide Request

### ISSUE THREAD

**Issue by tayamaYuto** [GoogleCloudPlatform/cloud-sql-python-connector#1188]
### Question

I want to access Cloud SQL from a local Docker container, but when implementing it with the Python Connector, it prompts me to run gcloud auth application-default login.

It works fine when not in a Docker environment after logging in, but how can I enable this authentication from within a Docker container?

(It would be a hassle to log in each time, so if there’s a better way, I’d like to know.)

### Code

```
def init_connection_pool(connector: Connector) -> Engine:
    instance_connection_name = os.environ["INSTANCE_CONNECTION_NAME"]
    db_user = os.environ["DB_USER"]
    # db_pass = os.environ["DB_PASS"]
    db_name = os.environ["DB_NAME"]

    def getconn():
        conn = connector.connect(
            instance_connection_name, # Cloud SQL Instance Connection Name
            "pg8000",
            user=db_user,
            db=db_name,
            enable_iam_auth=True,
            ip_type="public"  # "private" for private IP
        )
        return conn

    SQLALCHEMY_DATABASE_URL = "postgresql+pg8000://"

    engine = create_engine(
        SQLALCHEMY_DATABASE_URL , creator=getconn
    )
    return engine
```

**Comment by tayamaYuto** [comment]
I found that IAM automatic authentication is available. I’ll give it a try.

**Comment by jackwotherspoon** [comment]
Hi @tayamaYuto and thanks for raising a question on the Cloud SQL Python Connector! 😄 

We have a ["Credentials" section in our README](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector?tab=readme-ov-file#credentials) with detailed links that explain how the Python Connector sources Application Default Credentials (ADC). 

This [Set up Application Default Credentials](https://cloud.google.com/docs/authentication/provide-credentials-adc) is probably the most useful of the links to READ.

For a local Docker container the easiest method would probably be to volume mount a credentials file (either your personal user credentials file which is saved after running `gcloud auth application-default login` or a service account key file) and then set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to its file path.

This [blog](https://medium.com/datamindedbe/application-default-credentials-477879e31cb5) does a good job of highlighting how to do this, give it a read and let me know if you are able to get it working 😄

**Comment by tayamaYuto** [comment]
Thank you so much for your kind support.
The link you shared was really helpful, and it turned out to be the perfect solution for me.
Thanks again!

**Comment by jackwotherspoon** [comment]
My pleasure, great to hear it worked for you! 

Have a lovely week 😄
