### ISSUE TITLE
Improving Delayed Response Times for Requests in FastAPI with Cloud SQL

### ISSUE THREAD

**Issue by tayamaYuto** [GoogleCloudPlatform/cloud-sql-python-connector#1189]
### Question

I'm developing with FastAPI and Cloud SQL, and when I try to handle a simple GET request like in my code, it takes about 8 seconds to retrieve information. If I send consecutive GET requests, the response time is faster, but after some time, it again takes around 8 seconds.

Since this response time is slow for an optimal user experience, I’m looking to resolve this issue. I suspect the connection establishment part of my code is not placed optimally, but do you have any ideas or know of any existing Q&A that addresses this?

### Code
database.py
```Python
import os
from dotenv import load_dotenv

from sqlalchemy import create_engine
from sqlalchemy.engine import Engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from google.cloud.sql.connector import Connector

load_dotenv()

Base = declarative_base()

class Database:
    def __init__(self):
        self.connector = Connector()
        self.engine: Engine = None
        self.SessionLocal: sessionmaker = None

    def init_connection_pool(self) -> Engine:
        instance_connection_name = os.environ["INSTANCE_CONNECTION_NAME"]
        db_user = os.environ["DB_USER"]
        db_pass = os.environ["DB_PASS"]
        db_name = os.environ["DB_NAME"]

        def getconn():
            conn = self.connector.connect(
                instance_connection_name,  # Cloud SQL Instance Connection Name
                "pg8000",
                user=db_user,
                password=db_pass,
                db=db_name,
                ip_type="public"  # "private" for private IP
            )
            return conn

        SQLALCHEMY_DATABASE_URL = "postgresql+pg8000://"

        engine = create_engine(
            SQLALCHEMY_DATABASE_URL,
            creator=getconn
        )
        return engine

    def init(self):
        self.engine = self.init_connection_pool()
        self.SessionLocal = sessionmaker(
            autocommit=False,
            autoflush=False,
            bind=self.engine
        )
```

dps.py
```Python
from db.database import Database

database = Database()
database.init()

def get_db():
    db = database.SessionLocal()
    try:
        yield db
    finally:
        db.close()
```

main.py
```Python
from db.dps import get_db
@app.get("/")
def test(db :Session = Depends(get_db)):
    # DB process
    return test
```

**Comment by jackwotherspoon** [comment]
Hi @tayamaYuto thanks for the question! 😄 

> I'm developing with FastAPI and Cloud SQL

Can you share where you are deploying your application? Is it GKE, App Engine, Cloud Run?

If it is Cloud Run then it sounds like you are application is having slow "cold starts".

From the [Cloud Run docs](https://cloud.google.com/run/docs/tips/general#optimize_performance):

> Because instances are [scaled as needed](https://cloud.google.com/run/docs/about-instance-autoscaling), their startup time has impact on the latency of your service. While Cloud Run de-couples instance startup and request processing, it can happen that a request must wait for a new instance to be started to be processed, this notably happens when scaling from zero. This is called a "cold start".

The Cloud Run docs have some recommendations for [optimizing peformance](https://cloud.google.com/run/docs/tips/general#optimize_performance).

As a side-note for the Python Connector in a serverless environment, we recommend setting the Connector to be in "lazy refresh" mode. This may also help reduce the cold start latency.

```python
self.connector = Connector(refresh_strategy="LAZY")
```

If you are not deploying with Cloud Run, or continue to see additional request latency I will happily take a deeper look 😄

**Comment by tayamaYuto** [comment]
Thank you for your response.

Currently, I’m in the verification stage in my local environment and haven’t deployed yet, but I intend to use Cloud Run.

I understand that Cloud Run starts instances in response to requests. Since the setup and connection are happening repeatedly in my local development, I thought that the slow connection issues I’m experiencing locally might also occur in the deployed environment, which is why I asked.

If, in Cloud Run, the instance startup and request processing are indeed separated, then there’s a chance that the issue I’m concerned about might not occur. After deployment, if I still encounter the issue despite implementing the solution you provided, I’ll reach out again with further questions.

**Comment by jackwotherspoon** [comment]
@tayamaYuto Another suggestion for speeding up your overall application would be to use `asyncio`. The `asyncpg` driver allows [async usage of the Cloud SQL Python Connector](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector?tab=readme-ov-file#async-driver-usage) and  SQLAlchemy [`async_sessionmaker`](https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.async_sessionmaker) would help you achieve this.

**Comment by jackwotherspoon** [comment]
@tayamaYuto any luck speeding up your coldstarts?

**Comment by tayamaYuto** [comment]
@jackwotherspoon 
After deploying to Cloud Run, there were no issues with the communication speed with the database. Thank you for your support so far.

However, I am now facing a problem where secure communication between Cloud Run instances (Direct VPC Egress) is not functioning correctly. Is there a platform where I can ask questions to resolve this issue?

**Comment by jackwotherspoon** [comment]
Hi @tayamaYuto, glad it seems you were able to resolve the latency issues. 

> However, I am now facing a problem where secure communication between Cloud Run instances (Direct VPC Egress) is not functioning correctly. Is there a platform where I can ask questions to resolve this issue?

I would recommend starting a conversation on the [Google Cloud Serverless forum](https://www.googlecloudcommunity.com/gc/forums/filteredbylabelpage/board-id/cloud_serverless/label-name/Cloud%2520Run). 

This will allow serverless folks to hopefully point you in the right direction 🤞

I am going to close out this issue as it seems your initial Python Connector problem is no longer a worry, if you have any other issues with the Python Connector, feel free to re-open or create a new issue 😄
