### ISSUE TITLE
Use a single instance for Postgres tests

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/cloud-sql-python-connector#153]
Currently we're using a different instance for IAM tests and regular tests. We should just use one for both.

**Comment by kurtisvg** [comment]
This might be complicated by the fact that we need to reset the `ICM` used here between tests w.r.t the IAM Auth.

**Comment by enocom** [comment]
Closing -- we'll get this fixed as part of porting testing infrastructure to Terraform.
