### ISSUE TITLE
Certificate error after running program for 24 hours

### ISSUE THREAD

**Issue by elysianmichael** [GoogleCloudPlatform/cloud-sql-python-connector#182]
## Bug Description

SQL connection works fine, but after running program for 24 hours, I get a bad certificate error. 

My program launches AI platform instances every 12 hours. Once I do a db query after the 24 hour mark, I get this error:
Error: (2013, 'Lost connection to MySQL server during query ([SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2622))')

## Example code (or command)

```python
def executeQuery(query, params=None):
    db = getConnection()
    cursor = db.cursor(DictCursor)
    response = cursor.execute(query, params)
    result = cursor.fetchall()
    cursor.close()
    db.close()

    return result

async def executeQueryAsync(query, params=None):
    return await get_event_loop().run_in_executor(None, lambda: executeQuery(query, params=params))


def getConnection():
    return _getPyConnection()
    

def _getPyConnection():
    return connector.connect(
        instanceName,
        "pymysql",
        **dbCloudSqlConnector,
        autocommit=True
    )
```

## Environment

1. OS type and version: Windows
2. Python version: 3.8.5
2. Connector version: 1.0.2

**Comment by kurtisvg** [comment]
Hi @elysianmichael - can you provide us with some additional information:

- Does this happen EVERY time after 24 hours or some times?
- Do you have a full stack trace of the error? 

Additionally, if you can supply a full example (including code, imports, requirements, etc) that can replicate this consistently, that would be really helpful.

**Comment by jackwotherspoon** [comment]
@elysianmichael Closing for now. If you continue to run into the issue in the future, please feel free to open a new issue with additional details. Will happily look into it more with extra info.
Thanks!
