### ISSUE TITLE
AttributeError: 'Credentials' object has no attribute 'with_scopes'

### ISSUE THREAD

**Issue by eddie-scio** [GoogleCloudPlatform/cloud-sql-python-connector#24]
Reproduce:
```
python3 -m venv cloudsql_env
source cloudsql_env/bin/activate
pip install git+https://github.com/GoogleCloudPlatform/cloud-sql-python-connector@5b02e80149864369a0b8f6bc142d55c278a6e796

ipython
> from google.cloud.sql.connector import connector
> conn = connector.connect("<my-project>:us-central1:sql-1", "pymysql", user="root", password="<my-password", db="<my-db>")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-2f8a588de201> in <module>
      4     user="root",
      5     password="<>",
----> 6     db="<>")

~/workspace/scio/cloudsql_env/lib/python3.7/site-packages/google/cloud/sql/connector/connector.py in connect(instance_connection_string, driver, **kwargs)
     66 
     67     loop = _get_loop()
---> 68     icm = InstanceConnectionManager(instance_connection_string, loop)
     69     return icm.connect(driver, user=kwargs.pop("user"), **kwargs)

~/workspace/scio/cloudsql_env/lib/python3.7/site-packages/google/cloud/sql/connector/InstanceConnectionManager.py in __init__(self, instance_connection_string, loop)
    152 
    153         self._loop = loop
--> 154         self._auth_init()
    155         self._priv_key, pub_key = generate_keys()
    156         self._pub_key = pub_key.decode("UTF-8")

~/workspace/scio/cloudsql_env/lib/python3.7/site-packages/google/cloud/sql/connector/InstanceConnectionManager.py in _auth_init(self)
    373 
    374         credentials, project = google.auth.default()
--> 375         scoped_credentials = credentials.with_scopes(
    376             [
    377                 "https://www.googleapis.com/auth/sqlservice.admin",

AttributeError: 'Credentials' object has no attribute 'with_scopes'
```

**Comment by eddie-scio** [comment]
I've gotten a fix working with the following changes:

```
diff --git a/google/cloud/sql/connector/InstanceConnectionManager.py b/google/cloud/sql/connector/InstanceConnectionManager.py
index 1174ed8..54f28ee 100644
--- a/google/cloud/sql/connector/InstanceConnectionManager.py
+++ b/google/cloud/sql/connector/InstanceConnectionManager.py
@@ -22,7 +22,7 @@ import asyncio
 import aiohttp
 import concurrent
 import google.auth
-from google.auth.credentials import Credentials
+from google.auth.credentials import with_scopes_if_required, Credentials
 import google.auth.transport.requests
 import json
 import ssl
@@ -67,7 +67,7 @@ class InstanceMetadata:
         # files to be compatible with Windows.
         self._ca_fileobject.write(server_ca_cert.encode())
         self._cert_fileobject.write(ephemeral_cert.encode())
-        self.key_fileobject.write(private_key)
+        self._key_fileobject.write(private_key)
 
         self._ca_fileobject.seek(0)
         self._cert_fileobject.seek(0)
@@ -372,7 +372,7 @@ class InstanceConnectionManager:
         """
 
         credentials, project = google.auth.default()
-        scoped_credentials = credentials.with_scopes(
+        scoped_credentials = with_scopes_if_required(credentials,
             [
                 "https://www.googleapis.com/auth/sqlservice.admin",
                 "https://www.googleapis.com/auth/cloud-platform",
```

@crwilcox not sure if this was Ryan's intern project, but this would be super useful to me even if it's not actively developed.  I'm trying to connect to CloudSQL from Dataflow in Python, and I've been installing and starting the proxy on workers, which has been a pain and super flaky.  Do you mind making these fixes (they look like a few small bugs)?  I've confirmed that with them, I can make a connection using this library.

**Comment by crwilcox** [comment]
@eddie-scio, did you try fixing the var name without changing how we create credentials? I believe the scopes are required, which makes me hesistant about the changes to use `with_scopes_if_required`

**Comment by eddie-scio** [comment]
Thanks for the quick reply!  IIUC, the `Credentials` object that is returned may not have a `with_scopes` implementation (see [the base class](https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/credentials.py#L27)), as it may not be a child of [`Scoped`](https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/credentials.py#L255).  I believe these are the type of Credentials I get when I run with my owner account, as opposed to with a service account.  In my case, the credentials creation goes down [this path](https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/_default.py#L146), which is [a base `Credentials` object](https://github.com/googleapis/google-auth-library-python/blob/772dac6a6512230d32cb0dfae65a1a6aa9015049/google/auth/_default.py#L112).  This is also why if you have a service account activated, or if you're running on App Engine / GCE this logic is fine.

You're right that the scopes themselves are required --  I think `with_scopes_if_required` is a bit of a misleading name.

Perhaps a more clear thing to do would be to change
```
        credentials, project = google.auth.default()
        scoped_credentials = credentials.with_scopes(
            [
                "https://www.googleapis.com/auth/sqlservice.admin",
                "https://www.googleapis.com/auth/cloud-platform",
            ]
        )
```
to
```
 credentials, project = google.auth.default(scopes=[
                "https://www.googleapis.com/auth/sqlservice.admin",
                "https://www.googleapis.com/auth/cloud-platform",
            ]
)
```
[here](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/master/google/cloud/sql/connector/InstanceConnectionManager.py).  Note that will result in the same logic in [the underlying auth library.](https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/_default.py#L310)

**Comment by eddie-scio** [comment]
While I have you -- is there a reason this isn't mentioned in [the official Cloud docs](https://cloud.google.com/sql/docs/mysql/connect-external-app)?  If it's because it's experimental, is there a planned roadmap to maturity / support?

Thanks a ton.

**Comment by eddie-scio** [comment]
@crwilcox sorry for the ping -- do you have a timeline for when you might be able to get this in?  Have quite a bit of stuff blocked on moving our Dataflow pipelines away from `cloud_sql_proxy`.  Note that while the credentials stuff theoretically works on Dataflow, the variable change  with `self.key_fileobject` is necessary, otherwise initialization crashes.

**Comment by crwilcox** [comment]
Hi @eddie-scio this is an experiment at this time. Yes. That said, I should be able to address the issue you have discovered. I am looking into it now.

**Comment by eddie-scio** [comment]
Got it, thanks!

**Comment by crwilcox** [comment]
I dug into the auth thing. I am going to pass the scope to default. Really, it should avoid a duplication of auth so just a bit cleaner. PR incoming.
