### ISSUE TITLE
Destructor of `Connector` raises TimeoutError

### ISSUE THREAD

**Issue by komiya-atsushi** [GoogleCloudPlatform/cloud-sql-python-connector#292]
## Bug Description

When the destructor of the `Connector` was called, the destructor raises `TimeoutError`.

## Example code (or command)

https://github.com/komiya-atsushi/google-cloud-sql-connector-timeout

## Stacktrace
```
Exception ignored in: <function Connector.__del__ at 0x10274eb80>
Traceback (most recent call last):
  File "/***/python3.9/site-packages/google/cloud/sql/connector/connector.py", line 167, in __del__
  File "/***/python3.9/concurrent/futures/_base.py", line 448, in result
concurrent.futures._base.TimeoutError: 
```

## How to reproduce

  1. Clone https://github.com/komiya-atsushi/google-cloud-sql-connector-timeout
  2. `poetry install`
  3. Run `src/with_click.py`

```
CONNECTION_NAME=__your_connection_name__ \
DB_USER=__your_user__ \
DB_PASSWORD=__your_password__ \
export DATABASE_NAME=__your_db_name__ \
  poetry run python src/with_click.py
```

## Environment

1. OS type and version: macOS Monterey (12.2.1, Intel Mac)
2. Python version: `python --version`
    * `Python 3.9.10` ( `poetry run python -V` )
2. Connector version: 0.5.2

**Comment by jackwotherspoon** [comment]
@komiya-atsushi Thanks so much for raising this and providing detailed steps to reproduce. We made some changes to the cleanup steps that were in the latest release which is most likely the cause of this. I will attempt to reproduce the issue today and see about working on a fix, will let you know if I have any follow up questions.

Thanks again for raising, much appreciated.
