### ISSUE TITLE
Asyncio loop not cleared on closing / garbage collection

### ISSUE THREAD

**Issue by fuegoio** [GoogleCloudPlatform/cloud-sql-python-connector#409]
## Bug Description

We have a use case where we create connectors on demand from users to connect to Cloud SQL. This implies that we create a `Connector` instance and then `close()` it. After that, the reference to the connector no longer exists so Python GC it.

The issue we see is the exception `OSError`: `[Errno 24] Too many open files` raised at the creation of a connector after a long time. Especially, it is when the asyncio loop is created (see below the stacktrace).

## Example code

```python
with Connector(credentials=credentials) as connector:
    try:
        yield connector.connect(
            self.authentication.instance,
            "pg8000",
            user=self.authentication.username,
            password=self.authentication.password,
            db=self.authentication.database,
        )
        break
    except GoogleAPICallError:
        raise IssueException()
    except ClientResponseError as e:
        if e.status == 429:
            time.sleep(5)
            continue
        else:
            raise IssueException()

```

## Stacktrace
```
OSError: [Errno 24] Too many open files
  File "salescrew/core/celery.py", line 146, in __call__
    raise e
  File "salescrew/core/celery.py", line 143, in __call__
    self.run(*args, **kwargs)
  File "salescrew/connectors/routines.py", line 153, in update_users_from_integrations
    integration_user = connector.get_user(user_integration.id)
  File "salescrew/connectors/databases/postgresql.py", line 297, in get_user
    with self.connection as conn:
  File "contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "salescrew/connectors/databases/postgresql.py", line 346, in connection
    connector = Connector(credentials=credentials)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 67, in __init__
    self._loop: asyncio.AbstractEventLoop = asyncio.new_event_loop()
  File "asyncio/events.py", line 782, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "asyncio/events.py", line 673, in new_event_loop
    return self._loop_factory()
  File "asyncio/unix_events.py", line 64, in __init__
    super().__init__(selector)
  File "asyncio/selector_events.py", line 56, in __init__
    self._make_self_pipe()
  File "asyncio/selector_events.py", line 103, in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
  File "socket.py", line 607, in socketpair
    a, b = _socket.socketpair(family, type, proto)
```

## How to reproduce

  1. Create a lot of connectors one after another

## Environment

1. OS type and version:  Linux 5.15.55-1-lts
2. Python version: Python 3.10.4
2. Connector version: 0.6.2

## Proposal of resolution

I think because the connector uses the `run_forever` method of the loop, it doesn't clear itself after. Maybe a `self._loop.close()` might need to be done on the closing of the connector ? Or because the loop is used in a thread, we might also need to delete the thread at some point ?

**Comment by jackwotherspoon** [comment]
@fuegoio Thanks for raising this issue, much appreciated! 

I will look into this and try to reproduce it. I have a couple quick clarifying questions for you to help debug this further. When you say `"a lot of Connectors"`, do you have a specific range of how many you are referring to when this happens? Are all the `Connectors` open at the same time, or are most closed when the error occurs?

I believe you are probably right in your diagnosing of the issue. We use daemon threads for the `Connector` objects background tasks that by default get cleaned up when the Python process exits. This is not optimal for long-running processes and thus we should look at cleaning up the background threads and event loops upon closing of the `Connector` for better efficiency and usage of resources.

Thanks again for raising this and using the Python connector! We are always looking to make the package better and more efficient for our users.

Have a great day,
Jack

**Comment by fuegoio** [comment]
Hi Jack and thank you for looking into it!

> I will look into this and try to reproduce it. I have a couple quick clarifying questions for you to help debug this further. When you say `"a lot of Connectors"`, do you have a specific range of how many you are referring to when this happens? Are all the `Connectors` open at the same time, or are most closed when the error occurs?

I think the exact number is 1024! The `Connectors` are not open at the same time, they are all closed except one. We have as you said long-running processes because we use Celery workers processes to process import tasks from Cloud SQL.

If you think my solution is right, I can draft a PR ;)

> Thanks again for raising this and using the Python connector! We are always looking to make the package better and more efficient for our users.

Thank you for making it available to us!

**Comment by kurtisvg** [comment]
Hi @fuegoio,

Thanks for taking the time to open an issue. I definitely agree that we should be cleaning up the loop/thread in the situations where we've created it. 

I'm curious about your overall use case though - why is it you are using a new connector for each task as opposed to reusing one? Creating a new one means a lot more overhead in terms of SQL Admin API calls, where with a single connector those API calls can be cached more efficiently. 

Also, even after we fix this (if you still find a need to use separate connectors), you might still want to create your own thread with an async loop and manually pass that loop to all the connectors. This would give you some additional performance improvements (many less threads) but won't help much with the SQL Admin API quota issue.

**Comment by fuegoio** [comment]
Hi Kurtis,

> I'm curious about your overall use case though - why is it you are using a new connector for each task as opposed to reusing one? Creating a new one means a lot more overhead in terms of SQL Admin API calls, where with a single connector those API calls can be cached more efficiently.

We have a distributed system of import tasks. We schedule those tasks on a broker level, and then distribute them to a cluster of Docker containers running Celery workers. As we can have a different database for each of our customer, credentials are different and customizable for each task. We could have a store for those connectors, but because we run hundreds of containers, we won't really get any benefit I think.

But this issue arose especially because the `ClientResponseError` given by `aiohttp` was not caught by the library itself (which is weird I think?) when a 429 happened. This implied that we would need to have a retry pattern in case of soft errors like 429. But when using the same connector twice to connect after this error, we had another error about the fact that the connection was closed and not usable again. The solution was then to create a connector for each retry.

Because I think the rate limit is done on a credentials basis and that we run a lot of tasks to import millions of rows in a reasonnable time, we hit this rate limit once after a lot of retries (we honestly forgot a sleep after each try ahah).

> Also, even after we fix this (if you still find a need to use separate connectors), you might still want to create your own thread with an async loop and manually pass that loop to all the connectors. This would give you some additional performance improvements (many less threads) but won't help much with the SQL Admin API quota issue.

Yes we could do that! We don't really benefit from async because our code is synchronous for the moment (database driver on our end), we would be an improvement for the future.

Thanks a lot for your work :)

**Comment by kurtisvg** [comment]
> As we can have a different database for each of our customer, credentials are different and customizable for each task. We could have a store for those connectors, but because we run hundreds of containers, we won't really get any benefit I think.

If they are the same Cloud SQL instance per database, you should see a lot less `429s` than you are seeing right now :) 

>  But when using the same connector twice to connect after this error, we had another error about the fact that the connection was closed and not usable again.

This is interesting - if you have a sample code that reproduces I'd love to see it in a new issue. 

> We don't really benefit from async because our code is synchronous for the moment (database driver on our end), we would be an improvement for the future.

You don't need to benefit from using async to benefit from this. It would look something like this:
```
loop = asyncio.new_event_loop()
thread = Thread(target=self._loop.run_forever, daemon=True)
thead.start()

# ...

yield connector.connect(
    self.authentication.instance,
    "pg8000",
    user=self.authentication.username,
    password=self.authentication.password,
    db=self.authentication.database,
    loop=loop,
)
```

This will share one thread between all your different connectors, which means they will start up faster.
