### ISSUE TITLE
What is the correct connection URL format to connect to a Postgres database on Cloud SQL from Colab?

### ISSUE THREAD

**Issue by jackptoke** [GoogleCloudPlatform/cloud-sql-python-connector#417]
## Question
I am trying to connect to Cloud SQL using SQL Magic on Colab.  But I can't seem to figure out the correct connection URL format.
I've tried:
%sql postgresql+pg8000://db_username:password@[project_name:us-west1:instance_name:5432]/db_name
%sql postgresql+pg8000://db_username:password@xx.168.xxx.254:5432/db_name

Am I supposed to use both the host IP address and connection name?  How do I include both pieces of information in the connection URL string?

## Additional Context
Please reference any other relevant issues, PRs, descriptions, or screenshots here.

**Comment by jackwotherspoon** [comment]
@jackptoke Thanks for the great question! I am not super familiar with SQL Magic but from what I have seen it just uses SQLAlchemy under the hood to connect.

For some additional context, are you specifically attempting to use the Cloud SQL Python Connector with SQL Magic or just trying to connect to Cloud SQL in general with SQL Magic? 

I'll look into ways to configure SQL Magic with the Python Connector as we usually recommend using [SQLAlchemy's creator argument](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.creator) with a base URL for configuring connection pools:
```python
# create connection pool
pool = sqlalchemy.create_engine(
    "postgresql+pg8000://",
    creator=getconn, # see README for getconn definition
)
```
This isn't ideal for SQL Magic as it only looks at the connection URL, I'll have to see if there is a way to configure SQL Magic to take in the `creator` argument.

However, in the meantime you may be able to configure a connection to Cloud SQL with SQL Magic using a [TCP connection](https://cloud.google.com/sql/docs/postgres/connect-admin-proxy#expandable-1) or [Unix socket](https://cloud.google.com/sql/docs/postgres/connect-admin-proxy#expandable-2) connection.

The format of the Cloud SQL connection URL is referenced [here for TCP connections](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/cloud-sql/postgres/sqlalchemy/connect_tcp.py#L54-L55) and [here for Unix sockets](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/cloud-sql/postgres/sqlalchemy/connect_unix.py#L34-L38)

So it looks like your `%sql postgresql+pg8000://db_username:password@xx.168.xxx.254:5432/db_name` attempt may work (TCP connection) as long as you [authorize access for the IP address](https://cloud.google.com/sql/docs/postgres/configure-ip#add) of the Colab notebook to connect.

I'll look into the usage of SQL Magic with the Cloud SQL Python connector. Thanks again for raising this question!

Have a great day!

**Comment by jackwotherspoon** [comment]
@jackptoke after looking at the documentation a bit closer it seems that SQL Magic actually does support the `creator` argument for SQLAlchemy as one of its [command line options](https://github.com/catherinedevlin/ipython-sql#options).

Therefore using SQL Magic with the Python Connector should be theoretically possible (I haven't had the time to test it yet).

It would look something like this I believe:
```python
from google.cloud.sql.connector import Connector
import sqlalchemy

# creator function to return the database connection object
def getconn():
  # initialize Cloud SQL Python Connector object
  with Connector() as connector:
    conn = connector.connect(
        "project:region:instance",  # Cloud SQL instance connection name
        "pg8000",
        user="my-user",
        password="my-password",
        db="my-db-name"
    )
    return conn
``` 
And then your SQL Magic in a separate cell would just be:
```python
%sql postgresql+pg8000:// --creator getconn
```

Let me know if this ends up working for you as I am very eager to try it out myself!

Have a great day :)

**Comment by jackwotherspoon** [comment]
Closing this as answered. Feel free to re-open it if a further question arises or if there is anything else I can help with. Have a great day!
