### ISSUE TITLE
Python Connector Hangs From GKE

### ISSUE THREAD

**Issue by Rossco8** [GoogleCloudPlatform/cloud-sql-python-connector#470]
## Bug Description

Python connector is unable to connect to my DB from a GKE service. It appears the background ephemeral certificate refresh hangs

```
2022-09-14 13:01:35.509 AEST2022-09-14 03:01:35 DEBUG [instance.py:416] ['dev-project:us-east4:devdb']: Schedule refresh task cancelled.

2022-09-14 13:01:35.512 AESTTraceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535,
 in _request conn = await self._connector.connect( File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in 
connect proto = await self._create_connection(req, traces, timeout) File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", 
line 907, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) File "/usr/local/lib/python3.9/site-
packages/aiohttp/connector.py", line 1175, in _create_direct_connection transp, proto = await self._wrap_create_connection( File 
"/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection return await 
self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa File 
"/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection sock = await self._connect_sock( File 
"/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock await self.sock_connect(sock, address) File 
"/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect return await fut

```

## Example code (or command)

I can reliably reproduce the error with this test harness and small GKE service
https://gist.github.com/Rossco8/d8bc098bd69f1891dd9518d6905fc95b

It fails most of the time even with the `timeout` setting at 120

**Comment by jackwotherspoon** [comment]
Hi @Rossco8! Thanks for raising this issue and providing the code to reproduce. I will look into this and try to reproduce it myself. I will be back in touch if I have any questions.

Thanks again for your usage of the Python Connector and helping to make it better!

Have a great day,
Jack

**Comment by hessjcg** [comment]
Hi @Rosco8,  

I'm looking into reproducing this bug.  I'd like to confirm a few things about your setup so I can reproduce it correctly. Would you please answer a few of my questions about your setup below. 

- You are using Postgres database
  - You are using IAM Auth for postgres
  - Which postgress version are you using? 
  - In the network configuration, is "Public IP" enabled?
  - In the network configuration, is  "Private IP" enabled?
- You are using GKE 
  - Which kubernetes version are you using?
  - Is "Private cluster" enabled?
  - Is "VPC-native traffic routing" enabled? 
- You have a special node pool called "internal-nodepool" 
  - What kind of compute nodes are you using?
  - Is there anything special about the networking for this node pool?
- VPC topology (if you are using Private IP for the database)
  - Are the GKE cluster and the database connected to the same VPC?
  - Is there anything else unusual about the networking topology?
 
Thanks for your help. I'll continue reproducing this issue while I await your response.

-Jonathan

**Comment by Rossco8** [comment]
Hi @hessjcg, thanks for looking into this. See answers below. I hope it's not too much noise but I have added some more details in the GitHub gist showing the actual commands I used to create the SQL instance, GKE instance and network in case it helps

* You are using Postgres database
   You are using IAM Auth for postgres - **Yes, the service account is using IAM authentication and works without any issues from Cloud Run & Cloud Functions**
   Which postgress version are you using? **POSTGRES_14**
   In the network configuration, is "Public IP" enabled? **Yes both public and private is enabled**
   In the network configuration, is "Private IP" enabled? **Yes both public and private is enabled**
* You are using GKE
   Which kubernetes version are you using? **I use** `--cluster-version "latest"` **which gives me 1.24.4-gke.800**
   Is "Private cluster" enabled? **if you mean** `--enable-private-nodes` **yes**
   Is "VPC-native traffic routing" enabled? **Yes**
* You have a special node pool called "internal-nodepool"
   What kind of compute nodes are you using? **Spot instances of e2-standard-4**
   Is there anything special about the networking for this node pool?
* VPC topology (if you are using Private IP for the database)
   Are the GKE cluster and the database connected to the same VPC? **Yes - both in the same network** 
   Is there anything else unusual about the networking topology? I believe it is quite typical. It is a

**Comment by hessjcg** [comment]
Hi @Rossco8. Unfortunately we were unable to reproduce the network connection problems following the description of your environment. 

Based on your description of the error, I would guess that that some but not all packets are being dropped by a network device between your workload and your database. I would suggest your next step is to trace the network packets starting at your workload and investigate what might be interfering with the network traffic.
