### ISSUE TITLE
Usage with Alembic / SQL Alchemy ...

### ISSUE THREAD

**Issue by michealroberts** [GoogleCloudPlatform/cloud-sql-python-connector#609]
## Question

Reaching out to the community / experts because I am trying to run a Fast API app on Google Cloud Run with a Cloud MySQL database.

I'm wondering, are there any usage guides of running migrations with alembic against a Cloud MySQL database?

I've tried to define the alembic `run_migrations_online()` call as follows:

```py
def run_migrations_online():
    """Run migrations in 'online' mode.
    In this scenario we need to create an Engine
    and associate a connection with the context.
    """
    with engine.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata, compare_type=True
        )

        with context.begin_transaction():
            context.run_migrations()
``` 

Whereby the engine is defined as follows:

```py
import pymysql
from google.cloud.sql.connector import Connector, IPTypes
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

from app.core.config import settings


# Python Connector database connection function
def getconn() -> pymysql.connections.Connection:
    # Initialize the Connector object:
    with Connector() as connector:
        conn: pymysql.connections.Connection = connector.connect(
            settings.MYSQL_INSTANCE_CONNECTION_NAME,
            "pymysql",
            user=settings.MYSQL_USER,
            password=settings.MYSQL_PASSWORD,
            db=settings.MYSQL_DATABASE,
            ip_type=IPTypes.PUBLIC,  # IPTypes.PRIVATE for private IP
        )
    return conn


# We are using the Cloud SQL Auth Proxy, we connect to the database via a Unix socket:
engine = create_engine(
    "mysql+pymysql://",
    creator=getconn,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()
```

However, on running `alembic upgrade head` I get the following:

```
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('***')
```

Where I have redacted the sqladmin.googleapis.com connection string.

Are there any examples of using Cloud MySQL with Fast API that goes beyond a simple setup?

**Comment by michealroberts** [comment]
I also seem to get the same 400 BAD REQUEST error response when I use the usual:

```py
Base.metadata.create_all(bind=engine)
```

Is there something wrong with my setup perhaps? 🤔

**Comment by michealroberts** [comment]
So, closing this, I had one small issue -> I was using the wrong project to connect to the Cloud MySQL instance. D'oh! If anybody needs help with Alembic migrations and Cloud MySQL definitely reach out to me!

**Comment by jackwotherspoon** [comment]
@michealroberts Glad you got it sorted out! 

Do you have a public repo where I can see your usage of Alembic with the Python Connector? 😄 I'd love to see the working code and maybe include it somewhere in a sample for others to reference as well. I'm sure others will find it super useful in the future! 

Let me know! 

Have an awesome day 
-- Jack
