### ISSUE TITLE
url sqlalchemy property.

### ISSUE THREAD

**Issue by rorosan** [GoogleCloudPlatform/cloud-sql-python-connector#627]
### Question

Hi guys, when using the connector, the value of engine.url.database does not exit.

Is this done on purpose ?

**Comment by jackwotherspoon** [comment]
Hi @rorosan, thanks for the question about the Cloud SQL Python Connector! 😄 

> when using the connector, the value of engine.url.database does not exit

I'm going off the assumption you meant to say "**exist**" here and not "**exit**".

Yes this working as intended if you are creating a SQLAlchemy engine with the Python Connector through the use of SQLAlchemy's [`creator`](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.creator) argument. 

Here is how SQLAlchemy's docs explain the `creator` argument: 

> This creation function will be passed to the underlying connection pool and will be used to create all new database connections. Usage of this function causes connection parameters specified in the URL argument to be bypassed.

The key part worth noting is "causes connection parameters specified in the URL argument to be bypassed". The use of the `creator` argument bypasses URL params and thus does not set `engine.url.database` or any other `engine.url` params.

Hope this helps answer your question! 👍
