### ISSUE TITLE
Add support for lazy certificate refresh

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-python-connector#805]
### Feature Description

In serverless environments, when the CPU is throttled, the Python Connector will sometimes fail to refresh the certificate.

This is a feature request to allow callers to opt-in to a lazy refresh strategy, where no background tasks run and the cert is refreshed as needed.

**Comment by enocom** [comment]
Related to https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/992.

**Comment by jackwotherspoon** [comment]
Closed via #1093
