### ISSUE TITLE
Cloud Functions using Cloud SQL Python Connector gives "upstream request timeout"

### ISSUE THREAD

**Issue by abitama-satria-LO** [GoogleCloudPlatform/cloud-sql-python-connector#830]
### Question

I'm trying to connect my Cloud Function (2nd gen) instance to my Cloud SQL instance (a PostgreSQL database). I'm writing basically the same code with what you provide in [the example](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/cloud-sql/postgres/sqlalchemy/connect_connector.py).

The function works in my local machine, but if I deploy the same code, it will always return 504 "upstream request timeout". Why it gives that error?

I have checked that:
1. I used service account that has Cloud SQL Client role for the Cloud Function
2. the underlying Cloud Run service has been connected to the PostgreSQL instance after I initially deployed the code to Cloud Function

### Code

```Python
import functions_framework
import sqlalchemy
import json
from google.cloud.sql.connector import Connector, IPTypes
import pg8000


def connect_to_instance() -> sqlalchemy.engine.base.Engine:
    connector = Connector()

    def getconn() -> pg8000.dbapi.Connection:
        return connector.connect(
            "...", # the PostgreSQL's instance connection name here
            "pg8000",
            user     = "xyz",
            password = 'supersecret',
            db       = "db_name",
            ip_type  = IPTypes.PUBLIC
        )
    
    return sqlalchemy.create_engine(
        "postgresql+pg8000://",
        creator      = getconn,
        pool_size    = 5,
        max_overflow = 2,
        pool_timeout = 30,
        pool_recycle = 1800
    )


db = connect_to_instance()


@functions_framework.http
def hello_http(request):
    an_id = request.args["ID"]

    with db.connect() as conn:
        select_stmt = sqlalchemy.text(
            "SELECT col_1, col_2, col_3,"
            " FROM table_1"
            " WHERE col_1 = :some_id"
            " AND col_2 > 0"
        )
        
        fetch_result = conn.execute(
            select_stmt,
            {"some_id": an_id}
        ).fetchall()

    ost_inv = [list(o) for o in fetch_result]
    
    return json.dumps({"fetch_result": fetch_result}, default = str), 200, {"Content-Type": "application/json"}
```

### Additional Details

- Instances zone:
  - asia-southeast2

- Python version:
  - on local: 3.8 
  - on Cloud Function: 3.8, 3.9, 3.10, 3.11

- Cloud SQL Python Connector version: 1.4.1

- PostgreSQL instance:
  - version: 15
  - IP type: public
  - cloud SQL edition: enterprise
  - high availability: false
  - vCPU/memory/storage: 2/8/10

**Comment by jackwotherspoon** [comment]
Hi @abitama-satria-LO! Thanks for the detailed question! I don't see anything in your code that jumps out at me as the cause of the `504` (which means the Cloud Run service is timing out with each request). I will try and reproduce this sometime today and let you know if I have any clarifying questions 😄 

Thanks again for the question.

**Comment by jackwotherspoon** [comment]
I was able to re-produce this. I've turned this into a bug, looks like something is causing the connection to hang with Cloud Functions. Will hopefully have a fix shortly.

**Comment by abitama-satria-LO** [comment]
> I was able to re-produce this. I've turned this into a bug, looks like something is causing the connection to hang with Cloud Functions. Will hopefully have a fix shortly.

Hi Jack, thank you in advance! Hope everything going smoothly in your end

**Comment by abitama-satria-LO** [comment]
> I was able to re-produce this. I've turned this into a bug, looks like something is causing the connection to hang with Cloud Functions. Will hopefully have a fix shortly.

Oh btw if it helps, I deployed my instances in asia-southeast-2 zone

**Comment by jackwotherspoon** [comment]
Hi @abitama-satria-LO, thanks for the details! It turns out after investigating this a bit further it is actually not a bug in the Cloud SQL Python Connector but a documentation bug. I have put up a PR https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10576 to fix the documentation for Cloud Functions.

It turns out global variables that run background tasks can cause issues when run out side of the Cloud Function request context (because Cloud Functions only allocates compute when the first request is made). So Cloud Functions [recommends lazy initializing](https://cloud.google.com/functions/docs/samples/functions-tips-lazy-globals#functions_tips_lazy_globals-python) this type of global variable so that the variable is initialized within the request context.

Below is your provided code with lazy db initialization:
```python
import functions_framework
import sqlalchemy
import json
from google.cloud.sql.connector import Connector, IPTypes
import pg8000


def connect_to_instance() -> sqlalchemy.engine.base.Engine:
    connector = Connector()

    def getconn() -> pg8000.dbapi.Connection:
        return connector.connect(
            "...", # the PostgreSQL's instance connection name here
            "pg8000",
            user     = "xyz",
            password = 'supersecret',
            db       = "db_name",
            ip_type  = IPTypes.PUBLIC
        )
    
    return sqlalchemy.create_engine(
        "postgresql+pg8000://",
        creator      = getconn,
        pool_size    = 5,
        max_overflow = 2,
        pool_timeout = 30,
        pool_recycle = 1800
    )


# lazy initialization of global db
db = None


@functions_framework.http
def hello_http(request):
    an_id = request.args["ID"]
    # lazy init within request context
    global db
    if not db:
        db = connect_to_instance()
    with db.connect() as conn:
        select_stmt = sqlalchemy.text(
            "SELECT col_1, col_2, col_3,"
            " FROM table_1"
            " WHERE col_1 = :some_id"
            " AND col_2 > 0"
        )
        
        fetch_result = conn.execute(
            select_stmt,
            {"some_id": an_id}
        ).fetchall()

    ost_inv = [list(o) for o in fetch_result]
    
    return json.dumps({"fetch_result": fetch_result}, default = str), 200, {"Content-Type": "application/json"}
```

**Comment by abitama-satria-LO** [comment]
> Hi @abitama-satria-LO, thanks for the details! It turns out after investigating this a bit further it is actually not a bug in the Cloud SQL Python Connector but a documentation bug. I have put up a PR [GoogleCloudPlatform/python-docs-samples#10576](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10576) to fix the documentation for Cloud Functions.
> 
> It turns out global variables that run background tasks can cause issues when run out side of the Cloud Function request context (because Cloud Functions only allocates compute when the first request is made). So Cloud Functions [recommends lazy initializing](https://cloud.google.com/functions/docs/samples/functions-tips-lazy-globals#functions_tips_lazy_globals-python) this type of global variable so that the variable is initialized within the request context.
> 
> Below is your provided code with lazy db initialization:
> 
> ```python
> import functions_framework
> import sqlalchemy
> import json
> from google.cloud.sql.connector import Connector, IPTypes
> import pg8000
> 
> 
> def connect_to_instance() -> sqlalchemy.engine.base.Engine:
>     connector = Connector()
> 
>     def getconn() -> pg8000.dbapi.Connection:
>         return connector.connect(
>             "...", # the PostgreSQL's instance connection name here
>             "pg8000",
>             user     = "xyz",
>             password = 'supersecret',
>             db       = "db_name",
>             ip_type  = IPTypes.PUBLIC
>         )
>     
>     return sqlalchemy.create_engine(
>         "postgresql+pg8000://",
>         creator      = getconn,
>         pool_size    = 5,
>         max_overflow = 2,
>         pool_timeout = 30,
>         pool_recycle = 1800
>     )
> 
> 
> # lazy initialization of global db
> db = None
> 
> 
> @functions_framework.http
> def hello_http(request):
>     an_id = request.args["ID"]
>     # lazy init within request context
>     global db
>     if not db:
>         db = connect_to_instance()
>     with db.connect() as conn:
>         select_stmt = sqlalchemy.text(
>             "SELECT col_1, col_2, col_3,"
>             " FROM table_1"
>             " WHERE col_1 = :some_id"
>             " AND col_2 > 0"
>         )
>         
>         fetch_result = conn.execute(
>             select_stmt,
>             {"some_id": an_id}
>         ).fetchall()
> 
>     ost_inv = [list(o) for o in fetch_result]
>     
>     return json.dumps({"fetch_result": fetch_result}, default = str), 200, {"Content-Type": "application/json"}
> ```

Hi @jackwotherspoon, thank you so much for your explanation (and code sample). I just tested it, and it works!
