### ISSUE TITLE
Support aiomysql (create_async_engine & async_creator) for async connector like postgress?

### ISSUE THREAD

**Issue by rjjan** [GoogleCloudPlatform/cloud-sql-python-connector#883]
### Question

I use connector to Cloud SQL mysql
can i use aiomysql just like [asyncpg] (PostgreSQL)
just like 
"Async Driver Usage" section in https://pypi.org/project/cloud-sql-python-connector/ 
Thank you

**Comment by jackwotherspoon** [comment]
Hi @rjjan, thanks for asking a question on the Cloud SQL Python Connector 😄 

Unfortunately the Cloud SQL Python Connector does not currently support the [aiomysql](https://github.com/aio-libs/aiomysql) library, thus it will not work the same as `asyncpg`'s async driver usage. 

There is an open tracking issue #216 on our repo for its support. We also have a [WIP PR open](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/400) but it is blocked and has been blocked for a while on an [aiomysql feature PR](https://github.com/aio-libs/aiomysql/pull/786).

If you are using a Cloud SQL instance with a Private IP you could connect directly with `aiomysql` to your instance and not use this connector library. If that is something that interests you let me know and I can show you how to do it securely using an SSL connection and connecting directly to your instance.

**Comment by rjjan** [comment]
Hi @jackwotherspoon 

Really appreciate your answer.  Unfortunately I am using public IP Cloud SQL instance.

Seems that either I need to switch from mysql to postgress or to modify code to not using async engine.  (a bit headache) 

Thanks

**Comment by rjjan** [comment]
@jackwotherspoon It's an api service.   I plan to deploy it to Cloud Run.  
Currently I had this async issue when testing this container from local.
I haven't tried Cloud SQL Proxy but I'll look into it.
I was thinking Cloud Language Connector is the best practice to connect to Cloud SQL.  Any penalty if I go with Cloud SQL Auth Proxy ?

Thanks again.

**Comment by jackwotherspoon** [comment]
> I was thinking Cloud Language Connector is the best practice to connect to Cloud SQL. Any penalty if I go with Cloud SQL Auth Proxy ?

@rjjan No penalty to using the Proxy other than a bit more configuration, the Cloud SQL Proxy is a language agnostic version of the Python Connector essentially.

For Cloud Run I would recommend deploying the Cloud SQL Proxy as a sidecar using [Cloud Run's multi-container feature](https://cloud.google.com/blog/products/serverless/cloud-run-now-supports-multi-container-deployments). We have a Ruby example in our Cloud SQL Proxy repo that you can basically use the [exact same YAML](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/multi-container/ruby/multicontainer.yaml) for your Python application.  Just change the port to 3306 for MySQL.

Hope this helps lay the ground work for you 😄

**Comment by jackwotherspoon** [comment]
Going to close this as answered, feel free to re-open if issues persist 😄
