### ISSUE TITLE
Add support for gevent

### ISSUE THREAD

**Issue by bartsanchez** [GoogleCloudPlatform/cloud-sql-python-connector#969]
### Question

Hello,

I have a Flask app (using Flask-SqlAlchemy extension) that I am serving with Gunicorn.

If I try to use the connector (in the way it's defined for Flask-Sqlalchemy section, see attached code) using the worker class "_gevent_" I get the following error:

`google.cloud.sql.connector.exceptions.ConnectorLoopError: Connector event loop is running in current thread! Event loop must be attached to a different thread to prevent blocking code!`

However, using "_gthread_" (threads from the OS, if I am not wrong) and thus not monkey patching the code gives me no problems and the app starts properly (I guess it's because there's no event loop, so it's fine).

I'd like to know whether it's me doing something incorrect or if maybe it's because this connector is incompatible with monkey patching the code and using greenlet.

Thank you!

### Code

```Python
def getconn():
    conn = connector.connect(
        "FOO",
        "pg8000",
        user="MYUSER",
        enable_iam_auth=True,
        db="MYDB",
    )
    return conn
```

**Comment by bartsanchez** [comment]
Hello Jack! Thanks for the quick response.

[Gevent](https://www.gevent.org/intro.html) is a library to get asynchrony ("coroutine-based Python networking library") without the need to modify your non-async code by "monkey-patching" I/O bound, "blocking parts with compatible cooperative counterparts" ( [taken from this web](https://dev.to/lsena/gunicorn-worker-types-how-to-choose-the-right-one-4n2c) ).

So, I am not monkey patching directly, it's Gunicorn the one that is monkey patching all the possible functions when it starts the processes.

When your requests are mostly I/O bound tasks (that is my case), this is quite convenient since "it will allow it to scale to potentially thousands of concurrent requests on a single process".

From [this part ](https://www.gevent.org/intro.html#cooperative-multitasking) of the documentation, I can see that all greenlets are running in the same OS thread, which makes me think, after your answer, that it could be the case that then they are colliding with the event loop living in the background thread (or maybe there's not even a background thread, given the Gunicorn configuration for using gevent and the supposed new thread is running in a greenlet instead? and then the connector detects the collision and raise the error.? this is the part I get mostly lost).

I was thinking that maybe you or someone could have some experience using the connector for "monkey-patches" gevent code, but otherwise I think I can safely switch to use threads from the OS with Gunicorn (where the connector just works fine).

Sorry for my imprecision explaining the concepts but that's also why I raised the question in the first time, to try to bring some light about what could be happening and understanding if the usage of greenlets and the cloud-sql-python-connector was compatible (thus I was not configuring it properly) or maybe I was doing something conceptually wrong instead.

**Comment by jackwotherspoon** [comment]
@bartsanchez Thanks for the reply! Seems like our library conflicts with gevent from what you found. We try to optimize our synchronous code which is why we spin up the background thread that runs async tasks. 

I'll leave this open as a reminder for me to give gevent a try with the Connector myself to see if there is way to have the two work nicely together.

**Comment by bartsanchez** [comment]
Nice! Thank you!

Let me know if I can help somehow. I'll be glad.

**Comment by magnus0422** [comment]
Hello @jackwotherspoon I'm having the same issue and please let me know if you have any updates on it.
Thanks.

**Comment by enocom** [comment]
@magnus0422 are you using Flask?

A little toy reproduction would help us understand what's going wrong here.

**Comment by magnus0422** [comment]
@enocom Yes, I'm using Flask. Here is the discussion on stackoverflow.
https://stackoverflow.com/questions/77907693/how-to-use-eventlet-monkey-patch-and-google-cloud-sql-connector-together/77908089?noredirect=1#comment137349256_77908089

**Comment by enocom** [comment]
Thanks, @magnus0422. I don't see why we can't just properly fix this. Updated the title to make it clear that this library needs some work to function with gevent.

**Comment by magnus0422** [comment]
@enocom Hopefully you can provide me the solution soon. Thanks

**Comment by magnus0422** [comment]
Thank you @jackwotherspoon

**Comment by nioncode** [comment]
Is there any gunicorn worker that we can use to have asynchronous requests to the db working correctly? As per this issue, It seems like gevent is not supported or do we just need to set the event loop ourselves to not spawn a separate one?

@jackwotherspoon Can you provide a sample how to use the connector asynchronously with flask and gunicorn (though other http servers would also be fine)?

**Comment by jackwotherspoon** [comment]
> Can you provide a sample how to use the connector asynchronously with flask and gunicorn (though other http servers would also be fine)?

@nioncode Any reason not to just use Quart instead of Flask for an ASGI implementation instead of WSGI? [Flask recommends this themselves](https://flask.palletsprojects.com/en/3.0.x/async-await/#when-to-use-quart-instead) for true async support.

This would be my recommendation as right now the way `gevent` and `eventlet` have background worker threads conflicts with the Python Connector.

**Comment by nioncode** [comment]
No reason, just that we have a legacy code base for which we wanted to 'slap on' gevent for async without having to change much else. We'll definitely have a look at quart as well, I'm just afraid that some of our extensions will probably not work with it, that's why we wanted to try out gevent.

**Comment by jackwotherspoon** [comment]
@nioncode That makes total sense, I have bumped the priority of this issue based on your feedback. I will hope to address it in the near future 🤞
